version: '3.3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        depends_on:
            - flask
        ports:
            - "80:80"
        volumes:
            - "./conf/nginx.conf:/etc/nginx/nginx.conf"
        networks:
            - quiz_app

    flask:
        container_name: flask_app
        build:
            context: .
            dockerfile: ./flask_app/Dockerfile
        networks:
            - quiz_app

    db:
        image: postgres:14
        container_name: postgres
        environment:
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_DB: ${PSQL_DB}
            POSTGRES_PASSWORD: ${PSQL_PASS}
        volumes:
            - ./conf/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - postgresql:/var/lib/postgresql/data
        networks:
            - quiz_app


volumes:
    postgresql:


networks:
    quiz_app:
